[tool.commitizen]
version = "7.7.9"
version_files = [
    "Cargo.toml",
    "base/Cargo.toml",
    "config/Cargo.toml",
    "http_tools/Cargo.toml",
    "core/Cargo.toml",
    "adapters/diesel/Cargo.toml",
    "adapters/mem_db/Cargo.toml",
    "adapters/service/Cargo.toml",
    "adapters/notifier/Cargo.toml",
    "adapters/kv_db/Cargo.toml",
    "adapters/shared/Cargo.toml",
    "ports/api/Cargo.toml",
    "ports/cli/Cargo.toml",
]
name = "cz_conventional_commits"
tag_format = "v$version"
bump_message = "bump: $current_version → $new_version [skip-ci]"


[tool.commitizen.customize]
types = [
    { value = "chore", description = "Other changes that don't modify src or test files" },
]
