[tool.commitizen]
version = "7.8.2"
version_files = [
    "Cargo.toml",
    "base/Cargo.toml",
    "config/Cargo.toml",
    "http_tools/Cargo.toml",
    "core/Cargo.toml",
    "adapters/diesel/Cargo.toml",
    "adapters/mem_db/Cargo.toml",
    "adapters/service/Cargo.toml",
    "adapters/notifier/Cargo.toml",
    "adapters/kv_db/Cargo.toml",
    "adapters/shared/Cargo.toml",
    "ports/api/Cargo.toml",
    "ports/cli/Cargo.toml",
]
name = "cz_conventional_commits"
#tag_format = "v$version"
tag_format = "v$minor.$major.$patch-$prerelease$devrelease"
bump_message = "bump: $current_version → $new_version [skip-ci]"
bump_minor_prerelease = true
bump_patch_prerelease = true
bump_prerelease_separator = "-"


[tool.commitizen.customize]
types = [
    { value = "chore", description = "Other changes that don't modify src or test files" },
]
