include:
  - docker-compose.common.yaml

# ? ----------------------------------------------------------------------------
# ? SHARED CONFIGURATION
# ? ----------------------------------------------------------------------------
x-common-mycelium: &common-config
  networks: &common-networks
    - mycelium_net
  env_file:
    - .devcontainer/.env

# ? ----------------------------------------------------------------------------
# ? SERVICES DEFINITION
# ? ----------------------------------------------------------------------------
services:
  myc-api:
    # Inject all shared configs
    <<: *common-config

    container_name: myc-api
    build:
      context: .
      dockerfile: Dockerfile.dev
      no_cache: true
    restart: on-failure
    environment:
      - SETTINGS_PATH=/home/config.yaml
      - MYC_VAULT_TOKEN=${MYC_VAULT_TOKEN}
      - UTOIPA_REDOC_CONFIG_FILE=/home/redoc.config.json
    ports:
      - 8080:8080
    volumes:
      - ./settings/config.for-docker.yaml:/home/config.yaml:ro
      - ./test/mock/routes.yaml:/home/routes.yaml:ro
      - ./ports/api/src/api_docs/redoc.config.json:/home/redoc.config.json:ro
    depends_on:
      - myc-vault
      - myc-postgres
      - myc-redis
      - myc-jaeger
