# ? ----------------------------------------------------------------------------
# ? LOGGING SETTINGS
# ? ----------------------------------------------------------------------------
logging:
  backtrace: full
  rust_log: actix_web=debug,clean_base=debug,myc_api=debug

# ? ----------------------------------------------------------------------------
# ? AUTHENTICATION SETTINGS
#
# Authentication settings are used to configure the authentication methods.
# Default method is internal. It uses the database adapter plus the redis to
# flow along the users life cycle. Case the internal flow is enabled, user
# should configure the redis adapters using the adapters yaml file.
#
# It is possible to use third party authentication methods like google and azure
# oauth providers.
#
# ? ----------------------------------------------------------------------------
auth:
  # Internal authentication is the default authentication method. It uses the
  # database adapter plus the redis to flow along the users life cycle.
  internal:
    enable: true

  # Google third party authentication. It uses the google oauth2 to authenticate
  # the user. It requires a valid client id and secret.
  google:
    enable: true
    client_origin: http://localhost:3000
    token_expired_in: 60m
    token_max_age: 60
    jwt_secret: ""
    oauth_redirect_url: http://localhost:3000
    oauth_client_id: ""
    oauth_client_secret: ""

  # Azure third party authentication. It uses the azure oauth2 to authenticate
  # the user. It does not require a valid client id and secret. Working only
  # with the azure active directory.
  azure:
    enable: true
