# ? ----------------------------------------------------------------------------
# ? CORE CONFIGURATIONS
# ? ----------------------------------------------------------------------------
core:
  token_secret_key: ""
  token_expiration: 3600
  token_hmac_secret: ""
  token_email_notifier: ""

# ? ----------------------------------------------------------------------------
# ? SQL DATABASE ADAPTER SETTINGS
# ? ----------------------------------------------------------------------------
prisma:
  database_url: postgresql://postgres:postgres@175.20.10.2:5432/mycelium

# ? ----------------------------------------------------------------------------
# ? REDIS ADAPTER SETTINGS
# ? ----------------------------------------------------------------------------
redis:
  enable: true
  pool_max_open: 16
  pool_max_idle: 8
  pool_timeout_seconds: 1
  pool_expire_seconds: 60

# ? ----------------------------------------------------------------------------
# ? SMTP ADAPTER SETTINGS SETTINGS
# ? ----------------------------------------------------------------------------
smtp:
  enable: true
  host: ""
  username: ""
  password: ""

# ? ----------------------------------------------------------------------------
# ? AUTHENTICATION SETTINGS
#
# Authentication settings are used to configure the authentication methods.
# Default method is internal. It uses the database adapter plus the redis to
# flow along the users life cycle. Case the internal flow is enabled, user
# should configure the redis adapters using the adapters yaml file.
#
# It is possible to use third party authentication methods like google and azure
# oauth providers.
#
# ? ----------------------------------------------------------------------------
auth:
  # Internal authentication is the default authentication method. It uses the
  # database adapter plus the redis to flow along the users life cycle.
  internal:
    enable: true

  # Google third party authentication. It uses the google oauth2 to authenticate
  # the user. It requires a valid client id and secret.
  google:
    enable: true
    client_origin: http://localhost:3000
    token_expired_in: 60m
    token_max_age: 60
    jwt_secret: ""
    oauth_redirect_url: http://localhost:3000
    oauth_client_id: ""
    oauth_client_secret: ""

  # Azure third party authentication. It uses the azure oauth2 to authenticate
  # the user. It does not require a valid client id and secret. Working only
  # with the azure active directory.
  azure:
    enable: true

# ? ----------------------------------------------------------------------------
# ? API PORT SETTINGS SETTINGS
# ? ----------------------------------------------------------------------------
api:
  service_workers: 1
  service_port: 8080
  service_ip: 0.0.0.0
  allowed_origins:
    - http://localhost:8080
    - http://localhost:3000

  gateway_timeout: 60

  # ? --------------------------------------------------------------------------
  # ? LOGGING SETTINGS
  # ? --------------------------------------------------------------------------
  logging_level: actix_web=debug,clean_base=debug,myc_api=debug

  # ? --------------------------------------------------------------------------
  # ? API GATEWAY TLS SETTINGS
  #
  # TLS settings are used to configure the api gateway tls. It is possible to
  # configure the tls using the tls_cert_path and tls_key_path. Case the tls
  # cert path and tls key path are not configured, the api gateway will not be
  # able to connect to secure forwarding routes.
  #
  # ? --------------------------------------------------------------------------
  tls_cert_path: ""
  tls_key_path: ""

  # ? --------------------------------------------------------------------------
  # ? API GATEWAY ROUTE CONFIGURATION
  #
  # Routes file should be used to configure the api gateway routes. Routes file
  # should contains the following structure:
  #
  # services:
  #   - name: cat
  #     host: catfact.ninja
  #
  #     healthCheck:
  #       path: /health/
  #       healthResponseCodes:
  #         - 200
  #
  #     routes:
  #       - group: public
  #         methods:
  #           - GET
  #         downstreamUrl: /fact
  #         protocol: https
  #
  # ? --------------------------------------------------------------------------
  routes_file: test/mock/routes.yaml

# ? ----------------------------------------------------------------------------
# ? API PORT SETTINGS SETTINGS
# ? ----------------------------------------------------------------------------
cli: {}
