# ? ----------------------------------------------------------------------------
# ? CORE CONFIGURATIONS
# ? ----------------------------------------------------------------------------
core:
  accountLifeCycle:
    tokenExpiration: 3600
    tokenSecret:
      env: MYC_TOKEN_SECRET
    noreplyName: "Mycelium Keeper"
    noreplyEmail:
      env: MYC_TOKEN_EMAIL_NOTIFIER
    supportName: "Mycelium Keeper"
    supportEmail:
      env: MYC_TOKEN_SUPPORT_EMAIL

# ? ----------------------------------------------------------------------------
# ? SQL DATABASE ADAPTER SETTINGS
# ? ----------------------------------------------------------------------------
prisma:
  databaseUrl:
    env: MYC_DATABASE_URL

# ? ----------------------------------------------------------------------------
# ? NOTIFIER ADAPTER SETTINGS SETTINGS
#
# SMTP and QUEUE value should be set disabled or configured with the smtp host,
# username, and password. Case the smtp is disabled, the email notification will
# not be sent.
#
# ? ----------------------------------------------------------------------------
smtp: !enabled
  host: "smtp.gmail.com"
  username:
    env: MYC_SMTP_USERNAME
  password:
    env: MYC_SMTP_PASSWORD

queue: !enabled
  protocol: redis # should be rediss for secure connection
  hostname:
    env: MYC_REDIS_HOSTNAME
  password:
    env: MYC_REDIS_PASSWORD
  emailQueueName: emails
  consumeIntervalInSecs: 120

# ? ----------------------------------------------------------------------------
# ? AUTHENTICATION SETTINGS
#
# Authentication settings are used to configure the authentication methods.
# Default method is internal. It uses the database adapter plus the redis to
# flow along the users life cycle. Case the internal flow is enabled, user
# should configure the redis adapters using the adapters yaml file.
#
# It is possible to use third party authentication methods like google and azure
# oauth providers.
#
# ? ----------------------------------------------------------------------------
auth:
  # Internal authentication is the default authentication method. It uses the
  # database adapter plus the redis to flow along the users life cycle.
  internal: !enabled
    jwtSecret:
      env: MYC_INTERNAL_JWT_SECRET
    jwtExpiresIn: 43200 # 12 hours
    tmpExpiresIn: 300 # 5 minutes

  # Google third party authentication. It uses the google oauth2 to authenticate
  # the user. It requires a valid client id and secret.
  google: !enabled
    clientOrigin: http://localhost:3000
    jwtSecret:
      env: MYC_GOOGLE_JWT_SECRET
    jwtExpiresIn: 60m
    jwtMaxAge: 60
    oauthClientId:
      env: MYC_GOOGLE_OAUTH_CLIENT_ID
    oauthClientSecret:
      env: MYC_GOOGLE_OAUTH_CLIENT_SECRET
    oauthRedirectUrl: http://localhost:3000

  # Azure third party authentication. It uses the azure oauth2 to authenticate
  # the user. It does not require a valid client id and secret. Working only
  # with the azure active directory.
  azure: !enabled
    clientOrigin: http://localhost:3000
    # ! Should be collected from environment variable in production
    tenantId: "my_tenant_id"
    # ! Should be collected from environment variable in production
    clientId: "my_client_id"
    # ! Should be collected from environment variable in production
    clientSecret: "my_client_secret"
    redirectUrl: http://localhost:3000
    callbackPath: /auth/azure/callback

# ? ----------------------------------------------------------------------------
# ? API PORT SETTINGS SETTINGS
# ? ----------------------------------------------------------------------------
api:
  serviceIp: 0.0.0.0
  servicePort: 8080
  serviceWorkers: 1
  gatewayTimeout: 60
  allowedOrigins:
  - http://localhost:8080
  - http://localhost:3000
  # ? --------------------------------------------------------------------------
  # ? LOGGING SETTINGS
  # ? --------------------------------------------------------------------------
  logging:
    # Possible values: trace, debug, info, warn, error or specific level for
    # each module.
    level: actix_web=debug,mycelium_base=debug,myc_api=debug

    # Possible values: jsonl, ansi
    format: ansi

    # Specify the log target. Possible values: stdout, file, or jaeger
    #target: !jaeger
    #  name: mycelium-api
    #  # Hostname of the jaeger agent
    #  host: localhost
    #  # Allowed values:
    #  # - http
    #  # - https
    #  # - grpc
    #  protocol: grpc
    #  # Use (for default ports for each protocol):
    #  port: 4317

    # Example with file target
    #target: !file
    #  path: logs/api.log

    # Example with stdout target
    target: stdout

  # ? --------------------------------------------------------------------------
  # ? API GATEWAY TLS SETTINGS
  #
  # TLS settings are used to configure the api gateway tls. It is possible to
  # configure the tls using the tls_cert_path and tls_key_path. Case the tls
  # cert path and tls key path are not configured, the api gateway will not be
  # able to connect to secure forwarding routes.
  #
  # ? --------------------------------------------------------------------------
  tls: disabled
  #  tlsCertPath: "cert.pem"
  #  tlsKeyPath: "key.pem"

  # ? --------------------------------------------------------------------------
  # ? API GATEWAY ROUTE CONFIGURATION
  #
  # Routes file should be used to configure the api gateway routes. Routes file
  # should contains the following structure:
  #
  # services:
  #   - name: cat
  #     host: catfact.ninja
  #
  #     healthCheck:
  #       path: /health/
  #       healthResponseCodes:
  #         - 200
  #
  #     routes:
  #       - group: public
  #         methods:
  #           - GET
  #         downstreamUrl: /fact
  #         protocol: https
  #
  # ? --------------------------------------------------------------------------
  routes: test/mock/routes.yaml

# ? ----------------------------------------------------------------------------
# ? API PORT SETTINGS SETTINGS
# ? ----------------------------------------------------------------------------
cli: {}
