[package]
name = "mycelium-config"
version = "4.2.0"
edition = "2021"
authors = ["Samuel Galvão Elias <sgelias@outlook.com>"]
license = "Apache-2.0"
description = "Provide config manager features of the Mycelium project as and use-cases."
repository = "https://github.com/sgelias/mycelium"
readme = "./README.md"
keywords = [
    "authorization",
    "identity",
    "permission",
    "api-gateway",
    "mycelium",
]
categories = ["authentication", "network-programming"]

# ? ----------------------------------------------------------------------------
# ? DEPENDENCIES
# ? ----------------------------------------------------------------------------

[dependencies]
clean-base = "1.2"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"

[dev-dependencies]
tokio = { version = "1", features = ["full"] }

# ? ----------------------------------------------------------------------------
# ? LIBRARY
# ? ----------------------------------------------------------------------------

[lib]
name = "myc_config"
path = "src/lib.rs"
crate-type = ["staticlib", "lib"]
