-- Immutable audit trail for resource lifecycle events (see
-- .claude/specs/features/audit-log/design.md, "Data Models"). Mirrors the
-- Postgres `resource_audit_log` table with this adapter's established SQLite
-- type mapping (see migrations/2026-07-06-000000_init/up.sql header):
--   UUID        -> TEXT (hyphenated string, generated by the app)
--   JSONB       -> TEXT (serde_json string)
--   TIMESTAMPTZ -> TEXT (RFC3339 UTC, written by the app)
-- As with every other table in this schema, `id` has no DB-side default --
-- the app generates and supplies the UUID (see account/tenant/webhook, none
-- of which use a SQLite default for their TEXT primary key either).
-- `created_at` likewise has no default: it is always supplied by
-- emit_resource_audit_event at the moment the triggering use case succeeded,
-- not derived from insert time.
--
-- No FOREIGN KEY on resource_id/tenant_id: the row must outlive the resource
-- it describes (a deleted account keeps its audit history) -- same posture
-- as telegram_identity_audit in the Postgres schema.

CREATE TABLE resource_audit_log (
    id TEXT NOT NULL PRIMARY KEY,
    resource_type TEXT NOT NULL CHECK (resource_type IN
        ('account', 'account_meta', 'user', 'tenant', 'tenant_meta', 'guest_role', 'webhook')),
    resource_id TEXT NOT NULL,
    tenant_id TEXT,
    event TEXT NOT NULL CHECK (event IN ('created', 'updated', 'deleted')),
    performed_by TEXT NOT NULL,
    metadata TEXT NOT NULL DEFAULT '{}',
    created_at TEXT NOT NULL
);

CREATE INDEX idx_resource_audit_log_resource
    ON resource_audit_log (resource_id, created_at DESC);

CREATE INDEX idx_resource_audit_log_tenant
    ON resource_audit_log (tenant_id, created_at DESC)
    WHERE tenant_id IS NOT NULL;

-- Immutability: SQLite has no combined `BEFORE UPDATE OR DELETE` trigger
-- clause, so two separate triggers enforce the same guarantee as the
-- Postgres `prevent_resource_audit_log_mutation()` trigger function.
CREATE TRIGGER trg_resource_audit_log_no_update
BEFORE UPDATE ON resource_audit_log
BEGIN
    SELECT RAISE(ABORT, 'resource_audit_log is immutable');
END;

CREATE TRIGGER trg_resource_audit_log_no_delete
BEFORE DELETE ON resource_audit_log
BEGIN
    SELECT RAISE(ABORT, 'resource_audit_log is immutable');
END;
