-- SQLite schema for standalone mode. Mirrors the Postgres schema (sql/up.sql +
-- envelope-encryption migration) with SQLite-compatible types:
--   UUID        -> TEXT (hyphenated string, generated by the app)
--   JSONB       -> TEXT (serde_json string)
--   JSONB[]     -> TEXT (JSON array string)
--   TIMESTAMPTZ -> TEXT (RFC3339 UTC, written by the app)
--   BOOLEAN     -> INTEGER (0/1)
--   SERIAL      -> INTEGER PRIMARY KEY AUTOINCREMENT
-- Foreign keys are enforced (PRAGMA foreign_keys = ON, set on connection).

CREATE TABLE tenant (
    id TEXT NOT NULL PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    meta TEXT,
    status TEXT,
    created TEXT NOT NULL,
    updated TEXT,
    encrypted_dek TEXT,
    kek_version INTEGER NOT NULL DEFAULT 1,
    CONSTRAINT tenant_name_unique UNIQUE (name)
);

CREATE TABLE account (
    id TEXT NOT NULL PRIMARY KEY,
    name TEXT NOT NULL,
    created TEXT NOT NULL,
    created_by TEXT,
    updated TEXT,
    updated_by TEXT,
    is_active INTEGER NOT NULL DEFAULT 1,
    is_checked INTEGER NOT NULL DEFAULT 0,
    is_archived INTEGER NOT NULL DEFAULT 0,
    is_deleted INTEGER NOT NULL DEFAULT 0,
    is_default INTEGER NOT NULL DEFAULT 0,
    slug TEXT NOT NULL,
    account_type TEXT NOT NULL DEFAULT '{}',
    tenant_id TEXT,
    meta TEXT,
    CONSTRAINT unique_account_name UNIQUE (name, tenant_id),
    CONSTRAINT unique_account_slug UNIQUE (slug, tenant_id),
    FOREIGN KEY (tenant_id) REFERENCES tenant(id)
);

CREATE TABLE account_tag (
    id TEXT NOT NULL PRIMARY KEY,
    value TEXT NOT NULL,
    meta TEXT,
    account_id TEXT NOT NULL,
    CONSTRAINT unique_account_tag UNIQUE (value, account_id),
    FOREIGN KEY (account_id) REFERENCES account(id) ON DELETE CASCADE
);

CREATE TABLE "user" (
    id TEXT NOT NULL PRIMARY KEY,
    username TEXT NOT NULL,
    email TEXT NOT NULL,
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    is_active INTEGER NOT NULL DEFAULT 1,
    created TEXT NOT NULL,
    updated TEXT,
    account_id TEXT,
    is_principal INTEGER NOT NULL DEFAULT 0,
    mfa TEXT,
    CONSTRAINT unique_email_account UNIQUE (email, account_id),
    FOREIGN KEY (account_id) REFERENCES account(id)
);

CREATE TABLE identity_provider (
    user_id TEXT NOT NULL PRIMARY KEY,
    name TEXT,
    password_hash TEXT,
    CONSTRAINT unique_user_password_hash UNIQUE (user_id, password_hash),
    CONSTRAINT unique_user_name UNIQUE (user_id, name),
    FOREIGN KEY (user_id) REFERENCES "user"(id) ON DELETE CASCADE
);

CREATE TABLE owner_on_tenant (
    id TEXT NOT NULL PRIMARY KEY,
    tenant_id TEXT NOT NULL,
    owner_id TEXT NOT NULL,
    guest_by TEXT NOT NULL,
    created TEXT NOT NULL,
    updated TEXT,
    CONSTRAINT unique_tenant_owner UNIQUE (tenant_id, owner_id),
    FOREIGN KEY (tenant_id) REFERENCES tenant(id) ON DELETE CASCADE,
    FOREIGN KEY (owner_id) REFERENCES "user"(id) ON DELETE CASCADE
);

CREATE TABLE manager_account_on_tenant (
    id TEXT NOT NULL PRIMARY KEY,
    tenant_id TEXT NOT NULL,
    account_id TEXT NOT NULL,
    created TEXT NOT NULL,
    updated TEXT,
    CONSTRAINT unique_manager_tenant UNIQUE (tenant_id),
    CONSTRAINT unique_manager_account UNIQUE (account_id),
    CONSTRAINT unique_tenant_account UNIQUE (tenant_id, account_id),
    FOREIGN KEY (tenant_id) REFERENCES tenant(id) ON DELETE CASCADE,
    FOREIGN KEY (account_id) REFERENCES account(id) ON DELETE CASCADE
);

CREATE TABLE tenant_tag (
    id TEXT NOT NULL PRIMARY KEY,
    value TEXT NOT NULL,
    meta TEXT,
    tenant_id TEXT NOT NULL,
    CONSTRAINT unique_tenant_tag UNIQUE (value, tenant_id),
    FOREIGN KEY (tenant_id) REFERENCES tenant(id) ON DELETE CASCADE
);

CREATE TABLE guest_role (
    id TEXT NOT NULL PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    permission INTEGER NOT NULL DEFAULT 0,
    slug TEXT NOT NULL,
    system INTEGER NOT NULL DEFAULT 0,
    created TEXT NOT NULL,
    updated TEXT,
    CONSTRAINT unique_guest_role_name UNIQUE (name, permission),
    CONSTRAINT unique_guest_role_slug UNIQUE (slug, permission)
);

CREATE TABLE guest_role_children (
    parent_id TEXT NOT NULL,
    child_role_id TEXT NOT NULL,
    created_by TEXT NOT NULL,
    created TEXT NOT NULL,
    updated TEXT,
    PRIMARY KEY (parent_id, child_role_id),
    FOREIGN KEY (parent_id) REFERENCES guest_role(id),
    FOREIGN KEY (child_role_id) REFERENCES guest_role(id)
);

CREATE TABLE guest_user (
    id TEXT NOT NULL PRIMARY KEY,
    email TEXT NOT NULL,
    guest_role_id TEXT NOT NULL,
    created TEXT NOT NULL,
    updated TEXT,
    was_verified INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT unique_guest_user UNIQUE (email, guest_role_id),
    FOREIGN KEY (guest_role_id) REFERENCES guest_role(id)
);

CREATE TABLE guest_user_on_account (
    guest_user_id TEXT NOT NULL,
    account_id TEXT NOT NULL,
    created TEXT NOT NULL,
    permit_flags TEXT,
    deny_flags TEXT,
    PRIMARY KEY (guest_user_id, account_id),
    FOREIGN KEY (guest_user_id) REFERENCES guest_user(id) ON DELETE CASCADE,
    FOREIGN KEY (account_id) REFERENCES account(id)
);

CREATE TABLE error_code (
    code INTEGER NOT NULL,
    prefix TEXT NOT NULL,
    message TEXT NOT NULL,
    details TEXT,
    is_internal INTEGER NOT NULL DEFAULT 0,
    is_native INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY (prefix, code)
);

CREATE TABLE webhook (
    id TEXT NOT NULL PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    url TEXT NOT NULL,
    trigger TEXT NOT NULL,
    method TEXT DEFAULT 'POST',
    is_active INTEGER NOT NULL DEFAULT 1,
    created TEXT NOT NULL,
    created_by TEXT,
    updated TEXT,
    updated_by TEXT,
    secret TEXT,
    CONSTRAINT unique_webhook UNIQUE (name, url, trigger)
);

CREATE TABLE webhook_execution (
    id TEXT NOT NULL PRIMARY KEY,
    trigger TEXT NOT NULL,
    payload TEXT NOT NULL,
    payload_id TEXT NOT NULL,
    encrypted INTEGER DEFAULT 0,
    attempts INTEGER NOT NULL DEFAULT 0,
    created TEXT NOT NULL,
    attempted TEXT,
    status TEXT,
    propagations TEXT
);

CREATE TABLE token (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    meta TEXT NOT NULL,
    expiration TEXT NOT NULL
);

CREATE TABLE message_queue (
    id TEXT NOT NULL PRIMARY KEY,
    message TEXT NOT NULL,
    created TEXT NOT NULL,
    attempted TEXT,
    status TEXT NOT NULL,
    attempts INTEGER NOT NULL DEFAULT 0,
    error TEXT
);

CREATE TABLE healthcheck_logs (
    service_id TEXT NOT NULL,
    service_name TEXT NOT NULL,
    checked_at TEXT NOT NULL,
    status_code INTEGER NOT NULL,
    response_time_ms INTEGER NOT NULL,
    dns_resolved_ip TEXT,
    response_body TEXT,
    error_message TEXT,
    headers TEXT,
    content_type TEXT,
    response_size_bytes INTEGER,
    retry_count INTEGER,
    timeout_occurred INTEGER,
    PRIMARY KEY (service_id, checked_at)
);

-- Licensed resources view (mirrors the Postgres view; JSON columns are TEXT).
CREATE VIEW licensed_resources AS
SELECT DISTINCT
    ac.id AS acc_id,
    ac.name AS acc_name,
    ac.is_default AS is_acc_std,
    gr.id AS gr_id,
    gr.slug AS gr_slug,
    gr.permission AS gr_perm,
    gu.email AS gu_email,
    gu.was_verified AS gu_verified,
    ac.tenant_id AS tenant_id,
    ga.permit_flags AS permit_flags,
    ga.deny_flags AS deny_flags
FROM guest_user_on_account AS ga
JOIN guest_user AS gu ON ga.guest_user_id = gu.id
JOIN guest_role AS gr ON gr.id = gu.guest_role_id
JOIN account AS ac ON ac.id = ga.account_id
WHERE ac.is_deleted = 0
ORDER BY gu_email, gr_slug, acc_id, gr_id;

-- Public connection-string info view. Postgres JSON operators (-> / ? ) are
-- rewritten to SQLite JSON1 json_extract().
CREATE VIEW public_connection_string_info AS
SELECT
    id,
    json_extract(meta, '$.id') AS innerId,
    json_extract(meta, '$.accountId') AS accountId,
    json_extract(meta, '$.email') AS email,
    json_extract(meta, '$.name') AS name,
    expiration,
    json_extract(meta, '$.createdAt') AS createdAt,
    json_extract(meta, '$.scope') AS scope
FROM token
WHERE json_extract(meta, '$.token') IS NOT NULL
  AND json_extract(meta, '$.name') IS NOT NULL
  AND json_extract(meta, '$.id') IS NOT NULL
ORDER BY id DESC;
