[package]
name = "mycelium-app"
version = "3.0.1"
edition = "2021"
description = "Template for starting a Yew project using Trunk"
readme = "README.md"
repository = "https://github.com/yewstack/yew-trunk-minimal-template"
license = "MIT OR Apache-2.0"
keywords = ["authorization", "identity", "permission", "keeper"]
categories = ["http-client", "microservices"]

# ? ---------------------------------------------------------------------------
# ? DEPENDENCIES
# ? ---------------------------------------------------------------------------

[dependencies]
#gloo = "0.8.0"
#reqwasm = "0.5.0"
#serde = { version = "1.0.152", features = ["derive"] }
#serde_json = "1.0.93"
#uuid = { version = "1.3.0", features = ["serde", "v4", "js"] }
#wasm-bindgen = "0.2.80"
#wasm-bindgen-futures = "0.4"
#web-sys = { version = "0.3.61", features = ["HtmlInputElement", "Window"] }
yew = { version = "0.20", features = ["csr"] }
#yewdux = "0.9.2"

#[dependencies.mycelium-api]
#path = "../../ports/api"

# ? ---------------------------------------------------------------------------
# ? BINARIES
# ? ---------------------------------------------------------------------------

# [[bin]]
# name = "myc-app"
# path = "src/main.rs"
