name: Publish Crate from Release

on:
  #release:
  #  types: [published]
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    #- name: Run tests
    #  run: cargo test --verbose
    - name: Publish
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
      run: scripts/publish-all.sh --token "${CARGO_REGISTRY_TOKEN}" --verbose
